In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
os.chdir('E:/Machine Learning/Recommendation systems/Module 2 - Non Personalized Recommendations/Datasets')

In [5]:
Ratings=pd.read_csv("ratings.csv",encoding="ISO-8859-1")
Movies=pd.read_csv("movies.csv",encoding="ISO-8859-1")
Tags=pd.read_csv("tags.csv",encoding="ISO-8859-1")

In [6]:
#Display Ratings
Ratings

        userId  movieId  rating   timestamp
0        12882        1     4.0  1147195252
1        12882       32     3.5  1147195307
2        12882       47     5.0  1147195343
3        12882       50     5.0  1147185499
4        12882      110     4.5  1147195239
5        12882      150     3.5  1147195267
6        12882      158     2.0  1147185180
7        12882      165     4.0  1147195325
8        12882      260     4.0  1147195260
9        12882      296     5.0  1147195153
10       12882      318     5.0  1147195162
11       12882      356     5.0  1147185487
12       12882      364     3.5  1147195899
13       12882      380     2.5  1147195276
14       12882      457     4.0  1147195271
15       12882      480     3.5  1147185483
16       12882      515     3.5  1147185231
17       12882      527     4.0  1147195296
18       12882      552     2.5  1147185190
19       12882      588     3.0  1147195313
20       12882      589     2.5  1147185399
21       12882      590     3.0  1147195262
22       12882      592     3.5  1147195242
23       12882      593     4.5  1147195450
24       12882      648     4.0  1147195332
25       12882      780     0.5  1147195248
26       12882      784     1.5  1147185091
27       12882      805     4.5  1147185205
28       12882     1036     4.5  1147185376
29       12882     1094     3.0  1147185161
...        ...      ...     ...         ...
264475   90097     3978     3.5  1336143361
264476   90097     3996     4.0  1336151561
264477   90097     4022     4.0  1336150934
264478   90097     4308     4.5  1336144927
264479   90097     4367     5.0  1336151395
264480   90097     4370     2.0  1336143051
264481   90097     4386     0.5  1336149053
264482   90097     4963     5.0  1336143265
264483   90097     4993     4.0  1336144727
264484   90097     5010     4.5  1336144902
264485   90097     5299     5.0  1336147801
264486   90097     5418     4.5  1336143277
264487   90097     5944     3.0  1336144179
264488   90097     5952     4.0  1336144733
264489   90097     5970     3.5  1336147591
264490   90097     6564     4.5  1336151454
264491   90097     6565     4.5  1336143787
264492   90097     6942     5.0  1336145923
264493   90097     6947     4.0  1336147451
264494   90097     7147     5.0  1336144917
264495   90097     7153     4.0  1336144738
264496   90097     8665     4.5  1336143271
264497   90097     8984     4.5  1336143354
264498   90097    33679     4.0  1336151300
264499   90097    53322     4.5  1336143326
264500   90097    54286     5.0  1336143258
264501   90097    60069     4.5  1336144698
264502   90097    68358     5.0  1336144031
264503   90097    68954     5.0  1336146596
264504   90097    73017     4.0  1336148879

[264505 rows x 4 columns]

In [7]:
Ratings_mean=Ratings.groupby(['movieId'])[['rating']].mean().rename(columns = {'rating': 'Mean_rating'}).reset_index()

In [8]:
# Dsipla Mean ratings
Ratings_mean

      movieId  Mean_rating
0           1     3.793347
1           2     3.069892
2           3     2.923077
3           4     2.576923
4           5     2.848684
5           6     3.818182
6           7     3.250000
7           9     2.634615
8          10     3.335968
9          11     3.380734
10         12     2.617647
11         13     3.157895
12         14     3.365385
13         15     2.722222
14         16     3.901042
15         17     3.908000
16         18     3.312500
17         19     2.682540
18         20     2.564103
19         21     3.402439
20         22     3.056452
21         23     3.039216
22         24     2.816176
23         25     3.643939
24         26     3.361111
25         27     3.440000
26         28     3.942308
27         29     3.810811
28         31     3.120253
29         32     3.970519
...       ...          ...
2470    91542     3.691860
2471    91630     3.583333
2472    91658     3.740506
2473    92259     4.169231
2474    93840     3.716867
2475    94864     3.242268
2476    94959     3.931818
2477    95510     3.500000
2478    96079     3.768908
2479    96610     3.666667
2480    97304     3.830000
2481    97752     3.671429
2482    97913     3.860294
2483    97921     3.821429
2484    97938     3.772152
2485    98809     3.571429
2486    99114     4.061224
2487   102125     3.569149
2488   102445     3.651042
2489   104841     3.851351
2490   106487     3.689189
2491   106489     3.595238
2492   106782     3.863636
2493   106920     3.814103
2494   109374     4.005952
2495   109487     3.925676
2496   111362     3.850746
2497   111759     3.831169
2498   112556     4.000000
2499   112852     3.961039

[2500 rows x 2 columns]

In [9]:
# Calculating damped mean using alpha = 5
#sum of ratings by movie id
Ratings_sum=Ratings.groupby(['movieId'])[['rating']].sum().rename(columns = {'rating': 'sum_rating'}).reset_index()

In [10]:
#Display the ratings sum
Ratings_sum

      movieId  sum_rating
0           1      1881.5
1           2       856.5
2           3       228.0
3           4        33.5
4           5       216.5
5           6       756.0
6           7       266.5
7           9        68.5
8          10       844.0
9          11       368.5
10         12        89.0
11         13        60.0
12         14        87.5
13         15        98.0
14         16       749.0
15         17       488.5
16         18       238.5
17         19       676.0
18         20       100.0
19         21       558.0
20         22       189.5
21         23       155.0
22         24       191.5
23         25       481.0
24         26        60.5
25         27        86.0
26         28       102.5
27         29       423.0
28         31       246.5
29         32      1683.5
...       ...         ...
2470    91542       317.5
2471    91630       301.0
2472    91658       295.5
2473    92259       271.0
2474    93840       308.5
2475    94864       314.5
2476    94959       346.0
2477    95510       318.5
2478    96079       448.5
2479    96610       462.0
2480    97304       383.0
2481    97752       257.0
2482    97913       262.5
2483    97921       321.0
2484    97938       298.0
2485    98809       450.0
2486    99114       597.0
2487   102125       335.5
2488   102445       350.5
2489   104841       427.5
2490   106487       273.0
2491   106489       226.5
2492   106782       297.5
2493   106920       297.5
2494   109374       336.5
2495   109487       290.5
2496   111362       258.0
2497   111759       295.0
2498   112556       224.0
2499   112852       305.0

[2500 rows x 2 columns]

In [11]:
#Add a rating factor
Ratings_sum['sum_rating_factor']=Ratings_sum['sum_rating']+5*(Ratings["rating"].mean())

In [12]:
#Display the ratings
Ratings_sum

      movieId  sum_rating  sum_rating_factor
0           1      1881.5        1899.020312
1           2       856.5         874.020312
2           3       228.0         245.520312
3           4        33.5          51.020312
4           5       216.5         234.020312
5           6       756.0         773.520312
6           7       266.5         284.020312
7           9        68.5          86.020312
8          10       844.0         861.520312
9          11       368.5         386.020312
10         12        89.0         106.520312
11         13        60.0          77.520312
12         14        87.5         105.020312
13         15        98.0         115.520312
14         16       749.0         766.520312
15         17       488.5         506.020312
16         18       238.5         256.020312
17         19       676.0         693.520312
18         20       100.0         117.520312
19         21       558.0         575.520312
20         22       189.5         207.020312
21         23       155.0         172.520312
22         24       191.5         209.020312
23         25       481.0         498.520312
24         26        60.5          78.020312
25         27        86.0         103.520312
26         28       102.5         120.020312
27         29       423.0         440.520312
28         31       246.5         264.020312
29         32      1683.5        1701.020312
...       ...         ...                ...
2470    91542       317.5         335.020312
2471    91630       301.0         318.520312
2472    91658       295.5         313.020312
2473    92259       271.0         288.520312
2474    93840       308.5         326.020312
2475    94864       314.5         332.020312
2476    94959       346.0         363.520312
2477    95510       318.5         336.020312
2478    96079       448.5         466.020312
2479    96610       462.0         479.520312
2480    97304       383.0         400.520312
2481    97752       257.0         274.520312
2482    97913       262.5         280.020312
2483    97921       321.0         338.520312
2484    97938       298.0         315.520312
2485    98809       450.0         467.520312
2486    99114       597.0         614.520312
2487   102125       335.5         353.020312
2488   102445       350.5         368.020312
2489   104841       427.5         445.020312
2490   106487       273.0         290.520312
2491   106489       226.5         244.020312
2492   106782       297.5         315.020312
2493   106920       297.5         315.020312
2494   109374       336.5         354.020312
2495   109487       290.5         308.020312
2496   111362       258.0         275.520312
2497   111759       295.0         312.520312
2498   112556       224.0         241.520312
2499   112852       305.0         322.520312

[2500 rows x 3 columns]

In [13]:
Ratings_count=Ratings.groupby(['movieId'])[['rating']].count().rename(columns = {'rating': 'count_rating'}).reset_index()

In [14]:
#Display the ratings count
Ratings_count

      movieId  count_rating
0           1           496
1           2           279
2           3            78
3           4            13
4           5            76
5           6           198
6           7            82
7           9            26
8          10           253
9          11           109
10         12            34
11         13            19
12         14            26
13         15            36
14         16           192
15         17           125
16         18            72
17         19           252
18         20            39
19         21           164
20         22            62
21         23            51
22         24            68
23         25           132
24         26            18
25         27            25
26         28            26
27         29           111
28         31            79
29         32           424
...       ...           ...
2470    91542            86
2471    91630            84
2472    91658            79
2473    92259            65
2474    93840            83
2475    94864            97
2476    94959            88
2477    95510            91
2478    96079           119
2479    96610           126
2480    97304           100
2481    97752            70
2482    97913            68
2483    97921            84
2484    97938            79
2485    98809           126
2486    99114           147
2487   102125            94
2488   102445            96
2489   104841           111
2490   106487            74
2491   106489            63
2492   106782            77
2493   106920            78
2494   109374            84
2495   109487            74
2496   111362            67
2497   111759            77
2498   112556            56
2499   112852            77

[2500 rows x 2 columns]

In [15]:
Ratings_count['count_rating_factor']=Ratings_count['count_rating']+5

In [16]:
Ratings_count

      movieId  count_rating  count_rating_factor
0           1           496                  501
1           2           279                  284
2           3            78                   83
3           4            13                   18
4           5            76                   81
5           6           198                  203
6           7            82                   87
7           9            26                   31
8          10           253                  258
9          11           109                  114
10         12            34                   39
11         13            19                   24
12         14            26                   31
13         15            36                   41
14         16           192                  197
15         17           125                  130
16         18            72                   77
17         19           252                  257
18         20            39                   44
19         21           164                  169
20         22            62                   67
21         23            51                   56
22         24            68                   73
23         25           132                  137
24         26            18                   23
25         27            25                   30
26         28            26                   31
27         29           111                  116
28         31            79                   84
29         32           424                  429
...       ...           ...                  ...
2470    91542            86                   91
2471    91630            84                   89
2472    91658            79                   84
2473    92259            65                   70
2474    93840            83                   88
2475    94864            97                  102
2476    94959            88                   93
2477    95510            91                   96
2478    96079           119                  124
2479    96610           126                  131
2480    97304           100                  105
2481    97752            70                   75
2482    97913            68                   73
2483    97921            84                   89
2484    97938            79                   84
2485    98809           126                  131
2486    99114           147                  152
2487   102125            94                   99
2488   102445            96                  101
2489   104841           111                  116
2490   106487            74                   79
2491   106489            63                   68
2492   106782            77                   82
2493   106920            78                   83
2494   109374            84                   89
2495   109487            74                   79
2496   111362            67                   72
2497   111759            77                   82
2498   112556            56                   61
2499   112852            77                   82

[2500 rows x 3 columns]

In [17]:
#Merge together
Ratings_damped=pd.merge(Ratings_sum,Ratings_count[['movieId','count_rating','count_rating_factor']],on=['movieId'],how='left')

In [18]:
Ratings_damped

,movieId,sum_rating,sum_rating_factor,count_rating,count_rating_factor
0,1,1881.5,1899.020312,496,501
1,2,856.5,874.020312,279,284
2,3,228.0,245.520312,78,83
3,4,33.5,51.020312,13,18
4,5,216.5,234.020312,76,81
5,6,756.0,773.520312,198,203
6,7,266.5,284.020312,82,87
7,9,68.5,86.020312,26,31
8,10,844.0,861.520312,253,258
9,11,368.5,386.020312,109,114
10,12,89.0,106.520312,34,39
11,13,60.0,77.520312,19,24
12,14,87.5,105.020312,26,31
13,15,98.0,115.520312,36,41
14,16,749.0,766.520312,192,197
15,17,488.5,506.020312,125,130
16,18,238.5,256.020312,72,77
17,19,676.0,693.520312,252,257
18,20,100.0,117.520312,39,44
19,21,558.0,575.520312,164,169
20,22,189.5,207.020312,62,67
21,23,155.0,172.520312,51,56
22,24,191.5,209.020312,68,73
23,25,481.0,498.520312,132,137
24,26,60.5,78.020312,18,23
25,27,86.0,103.520312,25,30
26,28,102.5,120.020312,26,31
27,29,423.0,440.520312,111,116
28,31,246.5,264.020312,79,84
29,32,1683.5,1701.020312,424,429
...,...,...,...,...,...
2470,91542,317.5,335.020312,86,91
2471,91630,301.0,318.520312,84,89
2472,91658,295.5,313.020312,79,84
2473,92259,271.0,288.520312,65,70
2474,93840,308.5,326.020312,83,88
2475,94864,314.5,332.020312,97,102
2476,94959,346.0,363.520312,88,93
2477,95510,318.5,336.020312,91,96
2478,96079,448.5,466.020312,119,124
2479,96610,462.0,479.520312,126,131
2480,97304,383.0,400.520312,100,105
2481,97752,257.0,274.520312,70,75
2482,97913,262.5,280.020312,68,73
2483,97921,321.0,338.520312,84,89
2484,97938,298.0,315.520312,79,84
2485,98809,450.0,467.520312,126,131
2486,99114,597.0,614.520312,147,152
2487,102125,335.5,353.020312,94,99
2488,102445,350.5,368.020312,96,101
2489,104841,427.5,445.020312,111,116
2490,106487,273.0,290.520312,74,79
2491,106489,226.5,244.020312,63,68
2492,106782,297.5,315.020312,77,82
2493,106920,297.5,315.020312,78,83
2494,109374,336.5,354.020312,84,89
2495,109487,290.5,308.020312,74,79
2496,111362,258.0,275.520312,67,72
2497,111759,295.0,312.520312,77,82
2498,112556,224.0,241.520312,56,61
2499,112852,305.0,322.520312,77,82

In [19]:
Ratings_damped['damped_mean']=Ratings_damped['sum_rating_factor']/Ratings_damped['count_rating_factor']

In [20]:
Ratings_mean_dampmean=pd.merge(Ratings_mean[['movieId','Mean_rating']],Ratings_damped[['movieId','damped_mean']],on=['movieId'],how='left')

In [21]:
# Sorting to get top rated movies

Ratings_mean_dampmean = Ratings_mean_dampmean.sort_values(['Mean_rating'], ascending=False)

In [22]:
Ratings_mean_dampmean

      movieId  Mean_rating  damped_mean
189       318     4.364362     4.356802
422       858     4.315848     4.306888
632      1248     4.259259     4.195260
1355     2959     4.258503     4.252142
2110     7502     4.247423     4.210983
591      1203     4.246032     4.226909
1317     2859     4.220000     4.100677
608      1221     4.218462     4.207637
176       296     4.217781     4.212007
1210     2571     4.195359     4.190223
1737     4226     4.194617     4.187542
958      2019     4.191860     4.172431
1848     4973     4.190092     4.182279
908      1939     4.189655     4.088833
454       926     4.189655     4.135243
42         50     4.180617     4.173247
1972     6016     4.170251     4.158522
2473    92259     4.169231     4.121719
2174    26614     4.166667     4.115697
435       904     4.163900     4.150489
438       908     4.160891     4.145026
451       922     4.157407     4.128498
1407     3089     4.157407     4.102039
442       912     4.155709     4.144627
611      1224     4.153846     4.096848
667      1283     4.151786     4.098694
1578     3629     4.150000     4.091278
515      1041     4.144737     4.070240
2077     7156     4.141667     4.092620
912      1949     4.140625     4.054603
...       ...          ...          ...
1265     2720     2.000000     2.127463
880      1862     1.984848     2.184745
407       810     1.966667     2.351016
1099     2338     1.964789     2.066057
367       704     1.961538     2.390017
2113     7701     1.944444     2.076615
1761     4340     1.937500     2.111562
72        102     1.937500     2.540024
1124     2381     1.931818     2.092251
1155     2422     1.931373     2.071791
298       519     1.918182     2.050339
726      1381     1.911111     2.070406
1638     3821     1.880952     2.000299
1566     3564     1.866667     2.100580
1392     3054     1.844828     2.088833
1168     2456     1.842105     2.188346
781      1556     1.801020     1.883692
828      1681     1.794872     1.989098
237       393     1.743902     1.935224
1125     2382     1.740385     1.895093
1476     3268     1.736842     1.942333
380       737     1.732558     1.917090
859      1760     1.719298     1.863231
113       181     1.692308     1.984526
1914     5452     1.666667     1.808005
755      1453     1.642857     2.418359
840      1707     1.596491     1.750328
1126     2383     1.573171     1.783050
1570     3593     1.456140     1.621295
52         66     1.153846     1.806684

[2500 rows x 3 columns]